DROP TRIGGER IF EXISTS after_create;
DELIMITER $
CREATE TRIGGER after_create
AFTER INSERT ON `org`
  FOR EACH ROW
  BEGIN
    INSERT INTO
    org_permission_group
    SET
      org_id =                                  NEW.id,
      name =                                    'Super Users',
      machinelog_create =                       1,
      machinelog_edit_status =                  1,
      machinelog_edit_category =                1,
      machinelog_edit_downtime =                1,
      machinelog_delete_note_file =             1,
      machinelog_delete =                       1,
      schedule_create =                         1,
      schedule_edit =                           1,
      schedule_delete =                         1,
      admin_assign_users =                      1,
      admin_edit_procedures =                   1,
      admin_edit_tests =                        1,
      admin_manage_machines =                   1,
      daily_perform =                           1,
      daily_edit =                              1,
      daily_signoff =                           1,
      daily_approve =                           1,
      monthly_perform =                         1,
      monthly_edit =                            1,
      monthly_signoff =                         1,
      monthly_approve =                         1,
      quarterly_perform =                       1,
      quarterly_edit =                          1,
      quarterly_signoff =                       1,
      quarterly_approve =                       1,
      weekly_perform =                          1,
      weekly_edit =                             1,
      weekly_signoff =                          1,
      weekly_approve =                          1,
      yearly_perform =                          1,
      yearly_edit =                             1,
      yearly_signoff =                          1,
      yearly_approve =                          1,
      org_admin_equipment_fields =              1,
      org_admin_view_hidden_fields =            1,
      org_admin_manage_permission_groups =      1,
      org_admin_manage_password_settings =      1,
      org_admin_manage_auto_logout =            1,
      user_created_id =                         NEW.user_created_id,
      user_updated_id =                         NEW.user_updated_id,
      created_at =                                NOW(),
      updated_at =                                NOW();

    INSERT INTO
    org_permission_group
    SET
      org_id =                                  NEW.id,
      name =                                    'Supervisor',
      machinelog_create =                       1,
      machinelog_edit_status =                  1,
      machinelog_edit_category =                1,
      machinelog_edit_downtime =                1,
      machinelog_delete_note_file =             1,
      machinelog_delete =                       1,
      schedule_create =                         1,
      schedule_edit =                           1,
      schedule_delete =                         0,
      admin_assign_users =                      1,
      admin_edit_procedures =                   1,
      admin_edit_tests =                        1,
      admin_manage_machines =                   1,
      daily_perform =                           1,
      daily_edit =                              1,
      daily_signoff =                           1,
      daily_approve =                           0,
      monthly_perform =                         1,
      monthly_edit =                            1,
      monthly_signoff =                         1,
      monthly_approve =                         0,
      quarterly_perform =                       1,
      quarterly_edit =                          1,
      quarterly_signoff =                       1,
      quarterly_approve =                       0,
      weekly_perform =                          1,
      weekly_edit =                             1,
      weekly_signoff =                          1,
      weekly_approve =                          0,
      yearly_perform =                          1,
      yearly_edit =                             1,
      yearly_signoff =                          1,
      yearly_approve =                          0,
      org_admin_equipment_fields =              0,
      org_admin_view_hidden_fields =            1,
      org_admin_manage_permission_groups =      0,
      org_admin_manage_password_settings =      0,
      org_admin_manage_auto_logout =            0,
      user_created_id =                         NEW.user_created_id,
      user_updated_id =                         NEW.user_updated_id,
      created_at =                                NOW(),
      updated_at =                                NOW();

    INSERT INTO
    org_permission_group
    SET
      org_id =                                  NEW.id,
      name =                                    'User',
      machinelog_create =                       1,
      machinelog_edit_status =                  0,
      machinelog_edit_category =                1,
      machinelog_edit_downtime =                1,
      machinelog_delete_note_file =             0,
      machinelog_delete =                       0,
      schedule_create =                         1,
      schedule_edit =                           0,
      schedule_delete =                         0,
      admin_assign_users =                      0,
      admin_edit_procedures =                   0,
      admin_edit_tests =                        0,
      admin_manage_machines =                   0,
      daily_perform =                           1,
      daily_edit =                              0,
      daily_signoff =                           0,
      daily_approve =                           0,
      monthly_perform =                         1,
      monthly_edit =                            0,
      monthly_signoff =                         0,
      monthly_approve =                         0,
      quarterly_perform =                       1,
      quarterly_edit =                          0,
      quarterly_signoff =                       0,
      quarterly_approve =                       0,
      weekly_perform =                          1,
      weekly_edit =                             0,
      weekly_signoff =                          0,
      weekly_approve =                          0,
      yearly_perform =                          1,
      yearly_edit =                             0,
      yearly_signoff =                          0,
      yearly_approve =                          0,
      org_admin_equipment_fields =              0,
      org_admin_view_hidden_fields =            0,
      org_admin_manage_permission_groups =      0,
      org_admin_manage_password_settings =      0,
      org_admin_manage_auto_logout =            0,
      user_created_id =                         NEW.user_created_id,
      user_updated_id =                         NEW.user_updated_id,
      created_at =                                NOW(),
      updated_at =                                NOW();

      INSERT INTO
      org_permission_group
      SET
        org_id =                                  NEW.id,
        name =                                    'Reviewer',
        machinelog_create =                       0,
        machinelog_edit_status =                  0,
        machinelog_edit_category =                0,
        machinelog_edit_downtime =                0,
        machinelog_delete_note_file =             0,
        machinelog_delete =                       0,
        schedule_create =                         0,
        schedule_edit =                           0,
        schedule_delete =                         0,
        admin_assign_users =                      0,
        admin_edit_procedures =                   0,
        admin_edit_tests =                        0,
        admin_manage_machines =                   0,
        daily_perform =                           0,
        daily_edit =                              0,
        daily_signoff =                           0,
        daily_approve =                           0,
        monthly_perform =                         0,
        monthly_edit =                            0,
        monthly_signoff =                         0,
        monthly_approve =                         0,
        quarterly_perform =                       0,
        quarterly_edit =                          0,
        quarterly_signoff =                       0,
        quarterly_approve =                       0,
        weekly_perform =                          0,
        weekly_edit =                             0,
        weekly_signoff =                          0,
        weekly_approve =                          0,
        yearly_perform =                          0,
        yearly_edit =                             0,
        yearly_signoff =                          0,
        yearly_approve =                          0,
        org_admin_equipment_fields =              0,
        org_admin_view_hidden_fields =            0,
        org_admin_manage_permission_groups =      0,
        org_admin_manage_password_settings =      0,
        org_admin_manage_auto_logout =            0,
        user_created_id =                         NEW.user_created_id,
        user_updated_id =                         NEW.user_updated_id,
        created_at =                                NOW(),
        updated_at =                                NOW();

  END
$
DELIMITER ;
